In [1]:
import pandas

#Read all data
data = pandas.read_csv('data/gapminder_gdp_oceania.csv')
print(data)

       country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686
1  New Zealand     10556.57566     12247.39532     13175.67800

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928
1     14463.91893     16046.03728     16233.71770     17632.41040

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473
1     19007.19129     18363.32494     21050.41377     23189.80135

   gdpPercap_2007
0     34435.36744
1     25185.00911

In [2]:
#Use column values as row headings
data = pandas.read_csv('data/gapminder_gdp_oceania.csv', index_col='country')
print(data)

             gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country
Australia       10039.59564     10949.64959     12217.22686     14526.12465
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Australia       16788.62948     18334.19751     19477.00928     21888.88903
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Australia       23424.76683     26997.93657     30687.75473     34435.36744
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [3]:
#Find out more about the dataframe
#i.e. 2 rows: Australia, New Zealand;
#12 columns, each with 2 64-bit floating point values;
#Uses 208 bytes memory
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
gdpPercap_1952    2 non-null float64
gdpPercap_1957    2 non-null float64
gdpPercap_1962    2 non-null float64
gdpPercap_1967    2 non-null float64
gdpPercap_1972    2 non-null float64
gdpPercap_1977    2 non-null float64
gdpPercap_1982    2 non-null float64
gdpPercap_1987    2 non-null float64
gdpPercap_1992    2 non-null float64
gdpPercap_1997    2 non-null float64
gdpPercap_2002    2 non-null float64
gdpPercap_2007    2 non-null float64
dtypes: float64(12)
memory usage: 208.0+ bytes

In [4]:
#Columns variable stores data about dataframe columns
print(data.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [5]:
#Transpose data - Use columns as rows and rows as columns
print(data.T)

country           Australia  New Zealand
gdpPercap_1952  10039.59564  10556.57566
gdpPercap_1957  10949.64959  12247.39532
gdpPercap_1962  12217.22686  13175.67800
gdpPercap_1967  14526.12465  14463.91893
gdpPercap_1972  16788.62948  16046.03728
gdpPercap_1977  18334.19751  16233.71770
gdpPercap_1982  19477.00928  17632.41040
gdpPercap_1987  21888.88903  19007.19129
gdpPercap_1992  23424.76683  18363.32494
gdpPercap_1997  26997.93657  21050.41377
gdpPercap_2002  30687.75473  23189.80135
gdpPercap_2007  34435.36744  25185.00911

In [6]:
#Get summary statistics of columns containing numerical data
#Use the argument "include='all'" to include non-numeric data
print(data.describe())

       gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count        2.000000        2.000000        2.000000        2.000000
mean     10298.085650    11598.522455    12696.452430    14495.021790
std        365.560078      917.644806      677.727301       43.986086
min      10039.595640    10949.649590    12217.226860    14463.918930
25%      10168.840645    11274.086022    12456.839645    14479.470360
50%      10298.085650    11598.522455    12696.452430    14495.021790
75%      10427.330655    11922.958888    12936.065215    14510.573220
max      10556.575660    12247.395320    13175.678000    14526.124650

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count         2.00000        2.000000        2.000000        2.000000
mean      16417.33338    17283.957605    18554.709840    20448.040160
std         525.09198     1485.263517     1304.328377     2037.668013
min       16046.03728    16233.717700    17632.410400    19007.191290
25%       16231.68533    16758.837652    18093.560120    19727.615725
50%       16417.33338    17283.957605    18554.709840    20448.040160
75%       16602.98143    17809.077557    19015.859560    21168.464595
max       16788.62948    18334.197510    19477.009280    21888.889030

       gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
count        2.000000        2.000000        2.000000        2.000000
mean     20894.045885    24024.175170    26938.778040    29810.188275
std       3578.979883     4205.533703     5301.853680     6540.991104
min      18363.324940    21050.413770    23189.801350    25185.009110
25%      19628.685413    22537.294470    25064.289695    27497.598692
50%      20894.045885    24024.175170    26938.778040    29810.188275
75%      22159.406358    25511.055870    28813.266385    32122.777857
max      23424.766830    26997.936570    30687.754730    34435.367440

In [7]:
#Read Americas data, print summary statistics
americas = pandas.read_csv('data/gapminder_gdp_americas.csv')
print(americas.describe())

       gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count       25.000000       25.000000       25.000000       25.000000
mean      4079.062552     4616.043733     4901.541870     5668.253496
std       3001.727522     3312.381083     3421.740569     4160.885560
min       1397.717137     1544.402995     1662.137359     1452.057666
25%       2428.237769     2487.365989     2750.364446     3242.531147
50%       3048.302900     3780.546651     4086.114078     4643.393534
75%       3939.978789     4756.525781     5180.755910     5788.093330
max      13990.482080    14847.127120    16173.145860    19530.365570

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count       25.000000       25.000000       25.000000       25.000000
mean      6491.334139     7352.007126     7506.737088     7793.400261
std       4754.404329     5355.602518     5530.490471     6665.039509
min       1654.456946     1874.298931     2011.159549     1823.015995
25%       4031.408271     4756.763836     4258.503604     4140.442097
50%       5305.445256     6281.290855     6434.501797     6360.943444
75%       6809.406690     7674.929108     8997.897412     7807.095818
max      21806.035940    24072.632130    25009.559140    29884.350410

       gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
count       25.000000       25.000000       25.000000       25.000000
mean      8044.934406     8889.300863     9287.677107    11003.031625
std       7047.089191     7874.225145     8895.817785     9713.209302
min       1456.309517     1341.726931     1270.364932     1201.637154
25%       4439.450840     4684.313807     4858.347495     5728.353514
50%       6618.743050     7113.692252     6994.774861     8948.102923
75%       8137.004775     9767.297530     8797.640716    11977.574960
max      32003.932240    35767.433030    39097.099550    42951.653090

In [8]:
help(americas.head)
help(americas.tail)

Help on method head in module pandas.core.generic:

head(n=5) method of pandas.core.frame.DataFrame instance
    Returns first n rows

Help on method tail in module pandas.core.generic:

tail(n=5) method of pandas.core.frame.DataFrame instance
    Returns last n rows

In [9]:
#Return first 3 rows
americas.head(n=3)

,continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Americas,Argentina,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
1,Americas,Bolivia,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
2,Americas,Brazil,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825

In [10]:
#Return last 3 columns
americas_trans = americas.T
americas_trans.tail(n=3).T

   gdpPercap_1997 gdpPercap_2002 gdpPercap_2007
0         10967.3        8797.64        12779.4
1         3326.14        3413.26        3822.14
2         7957.98        8131.21         9065.8
3         28954.9          33329        36319.2
4         10118.1        10778.8        13171.6
5         6117.36        5755.26        7006.58
6         6677.05        7723.45        9645.06
7         5431.99        6340.65         8948.1
8          3614.1        4563.81        6025.37
9         7429.46        5773.04        6873.26
10        5154.83        5351.57        5728.35
11        4684.31        4858.35        5186.05
12        1341.73        1270.36        1201.64
13        3160.45        3099.73        3548.33
14        7121.92        6994.77        7320.88
15         9767.3        10742.4        11977.6
16        2253.02        2474.55        2749.32
17        7113.69        7356.03        9809.19
18         4247.4        3783.67        4172.84
19        5838.35        5909.02        7408.91
20        16999.4        18855.6        19328.7
21        8792.57        11460.6        18008.5
22        35767.4        39097.1        42951.7
23        9230.24           7727        10611.5
24        10165.5        8605.05        11415.8

In [11]:
americas_3col = americas_trans.tail(n=3).T
americas_3col.to_csv('americas_3col.csv')